### ISSUE TITLE
Unrecognized option '--stdin'

### ISSUE THREAD

**Issue by LeeTwelve** [gherasima/passwd-linux#2]
Hi, when I try change password of user I get `STDERR`: `passwd: unrecognized option '--stdin'`
I'm using ubuntu 16.04

**Comment by gherasima** [comment]
Thanks for your comment.
I will take a look in the comming week.

**Comment by gherasima** [comment]
I start to work on version 2 that will include a bug fix

**Comment by gherasima** [comment]
fixed on version 2.0.0
