### ISSUE TITLE
Feature Request : Custom response in the callback function

### ISSUE THREAD

**Issue by cjs840312** [gherasima/passwd-linux#4]
Current almost all the method's callback function returns strings as response
Ex :

    passwd.checkPass('username', 'password', function (error, response) {
        "use strict";
        if (error) {
            console.log(error);
        } else {
            console.log(response); // response: passwordCorrect or passwordIncorrect
        }
    });
We always need to implement decision statement such as 

    if( response === 'passwordCorrect' ) {
        // do something ...
    } else {
        // do something else...
    }
However it's seems not that elegant enough.
Is it possible to **customize** the response or simply return **bool type "true" or "false"**

**Comment by gherasima** [comment]
I start to work on version 2 that will include your request

**Comment by gherasima** [comment]
fixed on version 2.0.0
