### ISSUE TITLE
Error: Can't open shadow file!

### ISSUE THREAD

**Issue by varshadqz** [gherasima/passwd-linux#6]
Trying to run the code to check if the user exists: 
```
var passwd = require('passwd-linux');

var  username='abc'
passwd.userExist(username, function (err, response) {
    if (err) {
        console.log(err);
    } else {
        if (response) {
            console.log('User exist');
            console.log(response);
        } else {
            console.log('Unknown user');
            console.log(response);
        }
    }
});
```
~  
It returns error: Can't open shadow file!
what does this mean?

**Comment by gherasima** [comment]
In the code it's set:
### var shadowFile = '/etc/shadow';
That means the file that contains the password does not exist - /etc/shadow
Is this a linux system?

**Comment by varshadqz** [comment]
Yes, it is Linux and the **/etc/shadow** file also exits.

**Comment by varshadqz** [comment]
I run with sudo root privilege. It runs. Thank you.
